# Basic
title: 郝志
subtitle: 个人博客
description: 总有点东西值得记录！
# 头像里面的标题
avatarTitle: haozhi
# 头像里面的描述
avatarDesc:  电气|机器人
url: 

# Comment
comment:
    # disqus: 
    # duoshuo: 
    # cloudTie: 

# Social
social:
    weibo: 2932016415
    github: haozhih
    # twitter: 
    mail: haozhi118@126.com

# 百度统计 
# 使用博客模板请去掉或者更换 id 
baidu:
    id: cd205c44f221b51489bce574a1aec843   

# Google Analytics
# 使用博客模板请去掉或者更换 id
ga:
    id:    
    host:  


# 《----------------- 上面的信息修改成你自己的 ---------------------------》
#
#
#
#
#
# 《--------------- 下面的信息可以自行选择是否修改 ------------------------》


permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: 主页
    description: Blog
# Navigation buttons in the front page.s
nav:
    - {title: 文章, description: Archive, url: '/archive'}   
    - {title: 相册, description: Photo, url: '/photo'}      
    - {title: 关于, description: About me, url: '/some'}      
    

# Pagination
gems: [jekyll-paginate,jekyll-sitemap]
paginate: 15
paginate_path: "page/:num/"


